DROP DATABASE IF EXISTS mybatis;
CREATE DATABASE mybatis DEFAULT CHARACTER SET utf8;

use mybatis;
DROP TABLE IF EXISTS USER ;
CREATE TABLE user(
  id int(10) NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  age int(10) NOT NULL ,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO user VALUES(1, 'Kobe', 24);

